[package]
name = "rusty-ci"
version = "0.9.6"
authors = ["adam-mcdaniel <adam.mcdaniel17@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "A tool to generate buildbot projects from a YAML file"
documentation = "https://docs.rs/rusty-ci"
homepage = "https://github.com/adam-mcdaniel/rusty-ci"
repository = "https://github.com/adam-mcdaniel/rusty-ci"
categories = [
    "config", 
    "development-tools", 
    "command-line-utilities",
    "development-tools::testing"
]
default-run = "rusty-ci"
build = "build.rs"


# Added bin target
[[bin]]
name = "rusty-ci"
path = "src/bin.rs"


# Step tests
[[test]]
name = "step"
path = "tests/step.rs"

# Builder tests
[[test]]
name = "builder"
path = "tests/builder.rs"

# Worker tests
[[test]]
name = "scheduler"
path = "tests/scheduler.rs"

# Mail configuration tests
[[test]]
name = "mail"
path = "tests/mail.rs"

# Test Yaml operations
[[test]]
name = "yaml"
path = "tests/yaml.rs"

# Test String operations
[[test]]
name = "string"
path = "tests/string.rs"


[build-dependencies]
os_info = { version = "2.0.6", default-features = false }

[dependencies]
rand = "0.7.0"
rusty-yaml = "0.4.3"
clap = "2.33.0"
termcolor = "1.0.5"
version-compare = "0.0.9"
